baseURL = 'https://maxcyberspace.github.io/'
locale = 'en-us'
title = "Max's CyberSpace"
publishDir = "public"

[params]
  description = "Writings on tech, anime, food, and navigating life."
  author = "Max"

[permalinks]
  posts = "/:section/:title/"
  updates = "/updates/:year/:month/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
